# Version JDK8

FROM centos:7
MAINTAINER Gaurav Agarwal, bharatmicrosystems@gmail.com

RUN yum install -y java-1.8.0-openjdk-devel wget git maven openssh

# Create users and groups
RUN groupadd sftpgrp
RUN mkdir -p /var/transfers/sftp/user/incoming
RUN mkdir -p /var/transfers/sftp/user/outgoing
RUN useradd -s /bin/nologin -g sftpgrp -d /var/transfers/sftp/user user
RUN echo "user:password" | chpasswd

RUN chown -R user:sftpgrp /var/transfers/sftp/user
RUN chmod 2770 /var/transfers/sftp/user

COPY entrypoint.sh /tmp/entrypoint.sh
RUN chmod 777 /tmp/entrypoint.sh

VOLUME /var/transfers

EXPOSE 22
ENTRYPOINT ["/tmp/entrypoint.sh"]
#