# Version JDK8

FROM centos:7
MAINTAINER Gaurav Agarwal, bharatmicrosystems@gmail.com

RUN yum install -y java-1.8.0-openjdk-devel wget git maven openssh

# Create users and groups
RUN groupadd sftpgrp
RUN mkdir -p /var/transfers/sftp/user/incoming
RUN mkdir -p /var/transfers/sftp/user/outgoing
RUN useradd -s /bin/nologin -g sftpgrp -d /var/transfers/sftp/user user
echo "user:password" | chpasswd

RUN chown -R user:sftpgrp /var/transfers/sftp/user
RUN chmod 2770 /var/transfers/sftp/user

VOLUME /var/transfers

EXPOSE 22
CMD ["/bin/bash", "run"]
#
